name: advance_pdf_viewer_plus
description: A Flutter PDF viewer with support for Android and iOS.
version: 2.1.0
homepage: https://pub.dev/packages/advance_pdf_viewer_plus
repository: https://github.com/tulioccalazans/pdf_viewer
issue_tracker: https://github.com/tulioccalazans/pdf_viewer/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.6

dependency_overrides:
  sqflite: ^2.3.0
  platform: ^3.1.0

dev_dependencies:
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
